### ISSUE TITLE
Продать

### ISSUE THREAD

**Issue by Ecolograd** [edyatl/ecolograd#2]
Необходим пункт меню "Продать"
по структуре по аналогии с пунктом Продукция

**Comment by edyatl** [comment]
Не будет путаницы между "Продукция" - "Продать"? Может лучше "Закупка" или "Закупаем"?

**Comment by Ecolograd** [comment]
Да, лучше Закупаем02.08.2021, 18:53, "edyatl" ***@***.***>:
Не будет путаницы между "Продукция" - "Продать"? Может лучше "Закупка" или "Закупаем"?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
_________________________С уважением, Макеева Ю.И.тел. +7 904 610-92-23

**Comment by edyatl** [comment]
Добавлен раздел "Закупаем".
