### ISSUE TITLE
Кнопка продать вместо корзины

### ISSUE THREAD

**Issue by Ecolograd** [edyatl/ecolograd#3]
Смысл кнопки - после нажатия появляется окно формы:
-Вид пластика
-Объем
-Вес
-Местонахождение
-контактные данные: Имя и номер телефона в любом формате
-Возможность привязать фото материала

После заполнения формы сообщение о том, что менеджер свяжется в ближайшее время.

**Comment by edyatl** [comment]
В верхнее меню добавлена кнопка в виде телефонной трубки вместо корзины покупок. Также в раздел "Закупаем" на страницу каждого материала добавлена кнопка "Обратный Звонок", при нажатии этих кнопок открывается модал с предложением заказать обратный звонок, отправив имя и телефон. Форма работает через модуль "Feedback" и сообщения поступают через телеграмм бот сотрудникам подключенным к каналу.
